language: node_js
node_js:
- '7'
git:
  depth: 5
branches:
  only:
  - master
  - /^(\d+\.){2}\d+$/
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script: node ./scripts/tag-update $TRAVIS_TAG
after_success: npm run cover
deploy:
  provider: npm
  skip_cleanup: true
  email: alisahinozcelik@gmail.com
  api_key:
    secure: lK+qV/DBl8PLE86GZ29tEqBCeVsdLxahy1TzWMHgjfSEnmbjjity63zAkj8GJ4uh0JjYRsHkh/vDC0Qs3+gRbgCsMsjHbPPhLKwNZEzufajU7DcQM3uo3iiZ333xTSTQU+Ldb1uzL/nQwcoydPdF6jsjfOrlwJvOM1zqwOAfXrrNoiJU644vTLt9NCU9syPCK5s/7DVfB7rCQrxeNzSeRVL1FAYAhrOraJB68XAm9xRPAIltU6smKyn2XJ28iC5XO4rrltfjqvqn4KzvDkEPKehR0UmgQ0so+nqy9mxLNwLKXI+VXGzjEZO3vlv3VhwdJiSLAXx6+i+kMBwdDZz9rlP7ExX3HqISUiCyeUxhR9hN8x+D3tzfWCu4fFsY4+0aB5nu8czi/q8Sh5pexZ1Pi+d9fRm7ZtXkUr40Bq6iKUCIi3hYMvb7zrPgrhNbwoE+YAe5zG3w114J5f20AHnMOLLE0tyxkTeG8W2QmSufWuCpgyzOEPkmuUT2veA9U+HURjXUDmeZHA5pD3Md689tBmc4J68jpL8B/uISZJhH8btDL6f33NZu9e85Un9/R+zxQ5lJ0U1H61MfMmK49AgzXtNwXFNKjyvoDmRUnoI+Rc2jlfMa7SgiWc1BAf6Gq5MNwrJRb+azn7Mtrj5swnu+yMbBbXosecx8oRo+fgfyOCk=
  on:
    tags: true
    repo: gen-tech/scroll-manager
