language: node_js
node_js:
- '7'
git:
  depth: 5
branches:
  only:
  - master
  - /^(\d+\.){2}\d+$/
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script:
  - PATH=${PATH//:\.\/node_modules\/\.bin/}
after_success:
  - npm run cover
before_deploy:
  - npm run prepare-github-pages
deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    local-dir: docs
    on:
      branch: master
  - provider: script
    skip-cleanup: true
    script: npm run prepare-and-publish
    on:
      tags: true
