language: node_js
node_js:
- '7'
git:
  depth: 5
branches:
  only:
  - master
  - /^(\d+\.){2}\d+$/
before_script:
  - PATH=${PATH//:\.\/node_modules\/\.bin/}
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
after_success: npm run cover
before_deploy:
  - npm run prepare-github-pages
  - gtvu $TRAVIS_TAG --safe
deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    local-dir: docs
    on:
      branch: master
  - provider: npm
    skip_cleanup: true
    email: $NPM_EMAIL
    api_key: $NPM_TOKEN
    on:
      tags: true
      repo: gen-tech/scroll-manager
